import './globals.css'
import type { Metadata } from 'next'
import Navbar from '@/components/Navbar'
import Sidebar from "./Sidebar"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "500", "700"], // normal, medium, bold
  subsets: ["latin"], // include required subsets
  variable: "--font-roboto", // optional: CSS variable
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.variable} h-full`}>
      {/* Set body to h-screen to prevent the whole page from bouncing */}
      <body className='flex flex-col h-screen font-sans overflow-hidden'>
        
        {/* 1. Navbar: Keep it at the top */}
        <header className="z-50 shrink-0">
          <Navbar name='OrgName' signedIn={true}/>
        </header>

        <div className='flex flex-1 overflow-hidden'>
          {/* 2. Sidebar: Sticky/Fixed height with internal scroll if content is long */}
          <aside className='shrink-0 overflow-y-auto border-r border-gray-100 sticky top-0'>
            <Sidebar/>
          </aside>

          {/* 3. Main Content: This is the only part that scrolls */}
          <main className='grow overflow-y-auto bg-secondary-super-light/10'>
            {children}
          </main>
        </div>

      </body>
    </html>
  )
}