import "../globals.css"
import type { Metadata } from 'next'
import Navbar from '@/components/Navbar'
import Sidebar from "../Sidebar";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: 'Billing Enterprise ERP',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.variable} h-full`}>
      <body className='flex flex-col h-screen font-sans overflow-hidden'>
        
       
        

        <div className='flex flex-1 overflow-hidden relative'>
          
         
          <aside className=' shrink-0 z-50'>
            <Sidebar/>
          </aside>

         <div className='flex flex-col flex-1 bg-secondary-background' >
          <header className="z-[60] shrink-0">
          <Navbar name='OrgName' signedIn={true}/>
        </header>
          <main className='flex-1   overflow-y-auto no-scrollbar mr-5 relative bg-white rounded-2xl '>
           
            <div className="min-h-full">
              {children}
            </div>
          </main>

          </div> 
        </div>

      </body>
    </html>
  )
}